# Change these first
owner: svasseur # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Norsys
    url: https://www.norsys.fr
  - name: Norsys-daily
    url: https://norsys-daily.norsys.fr/
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor"
  introMessage: En cas de problèmes nous contacter 
  navbar:
    - title: Status
      href: /upptime
    - title: Norsys
      href: https://www.norsys.fr

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
